//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logica {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logica() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SUTEL.Shared.Logica", typeof(Logica).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv.
        /// </summary>
        public static string BitacoraTipoArchivo {
            get {
                return ResourceManager.GetString("BitacoraTipoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from dbo.ArchivoBandaAngostaCsv where IdArchivoCsv ={0}.
        /// </summary>
        public static string EliminarArchivoBandaAngosta {
            get {
                return ResourceManager.GetString("EliminarArchivoBandaAngosta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from dbo.ArchivoIMTFijasCsv where IdArchivoCsv ={0}.
        /// </summary>
        public static string EliminarArchivoIMTEstacionesFijas {
            get {
                return ResourceManager.GetString("EliminarArchivoIMTEstacionesFijas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from dbo.ArchivoTelevisionDigitalCsv  where IdArchivoCsv ={0}.
        /// </summary>
        public static string EliminarArchivoTelevisionDigitalCsv {
            get {
                return ResourceManager.GetString("EliminarArchivoTelevisionDigitalCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from dbo.DetalleBandaAngostaCsv where IdArchivoCsv={0}.
        /// </summary>
        public static string EliminarDetalleArchivoBandaAngosta {
            get {
                return ResourceManager.GetString("EliminarDetalleArchivoBandaAngosta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from dbo.DetalleArchivoIMTFijasCsv where IdArchivoCsv={0}.
        /// </summary>
        public static string EliminarDetalleArchivoIMTEstacionesFijas {
            get {
                return ResourceManager.GetString("EliminarDetalleArchivoIMTEstacionesFijas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from dbo.DetalleArchivoTelevisionDigitalCsv where IdArchivoCsv={0}.
        /// </summary>
        public static string EliminarDetalleArchivoTelevisionDigitalCsv {
            get {
                return ResourceManager.GetString("EliminarDetalleArchivoTelevisionDigitalCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ErrorAgregarArchivo {
            get {
                return ResourceManager.GetString("ErrorAgregarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La extención del archivo debe ser .csv o .mif.
        /// </summary>
        public static string ErrorExtenciónArchivo {
            get {
                return ResourceManager.GetString("ErrorExtenciónArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error no controlado {0}.
        /// </summary>
        public static string ErrorNoControlado {
            get {
                return ResourceManager.GetString("ErrorNoControlado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA.
        /// </summary>
        public static string FormatoArchivoBandaAngosta {
            get {
                return ResourceManager.GetString("FormatoArchivoBandaAngosta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMT.
        /// </summary>
        public static string FormatoArchivoIMT {
            get {
                return ResourceManager.GetString("FormatoArchivoIMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETL.
        /// </summary>
        public static string FormatoArchivoTVdigital {
            get {
                return ResourceManager.GetString("FormatoArchivoTVdigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string FormularioExcel {
            get {
                return ResourceManager.GetString("FormularioExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string FormularioMixto {
            get {
                return ResourceManager.GetString("FormularioMixto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string FormularioWeb {
            get {
                return ResourceManager.GetString("FormularioWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo &lt;strong&gt;{0}&lt;/strong&gt; fue eliminado exitosamente..
        /// </summary>
        public static string MensajeArchivoEliminadoCorectamente {
            get {
                return ResourceManager.GetString("MensajeArchivoEliminadoCorectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo fue insertado exitosamente.
        /// </summary>
        public static string MensajeArchivoInsertado {
            get {
                return ResourceManager.GetString("MensajeArchivoInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo &lt;strong&gt;{0}&lt;/strong&gt; no fue eliminado exitosamente..
        /// </summary>
        public static string MensajeArchivoNoFueEliminado {
            get {
                return ResourceManager.GetString("MensajeArchivoNoFueEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertado exitosamente.
        /// </summary>
        public static string MensajeBitacoraInsertar {
            get {
                return ResourceManager.GetString("MensajeBitacoraInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reemplazado exitosamente.
        /// </summary>
        public static string MensajeBitacoraReemplazar {
            get {
                return ResourceManager.GetString("MensajeBitacoraReemplazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea eliminar el archivo: &lt;strong&gt;{0}&lt;/strong&gt;?.
        /// </summary>
        public static string MensajeConfirmacionEliminaArchivo {
            get {
                return ResourceManager.GetString("MensajeConfirmacionEliminaArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El archivo: &lt;strong&gt;{0}&lt;/strong&gt; no está cargado actualmente.&quot;.
        /// </summary>
        public static string MensajeError_ArchivoNocargado {
            get {
                return ResourceManager.GetString("MensajeError ArchivoNocargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo: &lt;strong&gt;{0}&lt;/strong&gt; no está cargado actualmente..
        /// </summary>
        public static string MensajeErrorArchivoNoCargador {
            get {
                return ResourceManager.GetString("MensajeErrorArchivoNoCargador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo: &lt;strong&gt;{0}&lt;/strong&gt; no cumple con el formato csv..
        /// </summary>
        public static string MensajeErrorArchivoNoCumpleFormato {
            get {
                return ResourceManager.GetString("MensajeErrorArchivoNoCumpleFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo: &lt;strong&gt;{0}&lt;/strong&gt; no cumple con el formato csv..
        /// </summary>
        public static string MensajeErrorArchivoNoCumpleFormatoCSVMIF {
            get {
                return ResourceManager.GetString("MensajeErrorArchivoNoCumpleFormatoCSVMIF", resourceCulture);
            }
        }
    }
}
