//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraIndicador
    {
        public System.Guid IdBitacoIndicador { get; set; }
        public System.Guid IdDetalleRegistroIndicador { get; set; }
        public int IdUsuario { get; set; }
        public string ValorAnterior { get; set; }
        public string ValorNuevo { get; set; }
        public string Justificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual DetalleRegistroIndicador DetalleRegistroIndicador { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
