//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraExcepcion
    {
        public System.Guid IdExcepcion { get; set; }
        public string NombreAplicacion { get; set; }
        public string NombreServidor { get; set; }
        public string NombreUsuario { get; set; }
        public string NivelExcepcion { get; set; }
        public string Capa { get; set; }
        public string Mensaje { get; set; }
        public string Stacktrace { get; set; }
        public string InnerException { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
