//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constructor()
        {
            this.ConstructorCriterio = new HashSet<ConstructorCriterio>();
            this.SolicitudConstructor = new HashSet<SolicitudConstructor>();
        }
    
        public System.Guid IdConstructor { get; set; }
        public string IdIndicador { get; set; }
        public int IdFrecuencia { get; set; }
        public Nullable<int> IdDesglose { get; set; }
        public System.DateTime FechaCreacionConstructor { get; set; }
        public byte Borrado { get; set; }
        public Nullable<int> IdDireccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructorCriterio> ConstructorCriterio { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual Frecuencia Frecuencia { get; set; }
        public virtual Frecuencia Frecuencia1 { get; set; }
        public virtual Indicador Indicador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudConstructor> SolicitudConstructor { get; set; }
    }
}
