//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRegistroIndicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleRegistroIndicador()
        {
            this.BitacoraIndicador = new HashSet<BitacoraIndicador>();
        }
    
        public System.Guid IdDetalleRegistroindicador { get; set; }
        public System.Guid IdRegistroIndicador { get; set; }
        public System.Guid IdConstructorCriterio { get; set; }
        public int IdTipoValor { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdCanton { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public int Anno { get; set; }
        public int NumeroDesglose { get; set; }
        public string Valor { get; set; }
        public string Comentario { get; set; }
        public byte Modificado { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdDistrito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraIndicador> BitacoraIndicador { get; set; }
        public virtual Canton Canton { get; set; }
        public virtual ConstructorCriterioDetalleAgrupacion ConstructorCriterioDetalleAgrupacion { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual RegistroIndicador RegistroIndicador { get; set; }
        public virtual TipoValor TipoValor { get; set; }
    }
}
