//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleIndicadorCruzado
    {
        public System.Guid IdDetalleIndicadorCruzado { get; set; }
        public string IdIndicadorCruzado { get; set; }
        public string IdIndicadorExterno { get; set; }
        public string IdIndicador { get; set; }
        public string IdIndicadorInterno { get; set; }
    
        public virtual IndicadorExterno IndicadorExterno { get; set; }
        public virtual IndicadorCruzado IndicadorCruzado { get; set; }
        public virtual Indicador Indicador { get; set; }
        public virtual Indicador Indicador1 { get; set; }
    }
}
