//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InidicadorUmbralPeso
    {
        public int IdUmbralPeso { get; set; }
        public string IdIndicador { get; set; }
        public Nullable<decimal> Umbral { get; set; }
        public Nullable<decimal> PesoRelativo { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
        public string UsuarioUltimaModificacion { get; set; }
    
        public virtual Indicador Indicador { get; set; }
    }
}
