//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroIndicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistroIndicador()
        {
            this.DetalleRegistroIndicador = new HashSet<DetalleRegistroIndicador>();
        }
    
        public System.Guid IdRegistroIndicador { get; set; }
        public System.Guid IdSolicitudConstructor { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistroIndicador { get; set; }
        public string Comentario { get; set; }
        public string Justificado { get; set; }
        public byte Bloqueado { get; set; }
        public byte Borrado { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRegistroIndicador> DetalleRegistroIndicador { get; set; }
        public virtual SolicitudConstructor SolicitudConstructor { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
