//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regla
    {
        public System.Guid IdConstructorCriterio { get; set; }
        public string ValorLimiteInferior { get; set; }
        public string ValorLimiteSuperior { get; set; }
        public System.DateTime FechaCreacionRegla { get; set; }
        public byte Borrado { get; set; }
    
        public virtual ConstructorCriterioDetalleAgrupacion ConstructorCriterioDetalleAgrupacion { get; set; }
    }
}
