//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolAccionPantalla
    {
        public int IdRol { get; set; }
        public int IdPantalla { get; set; }
        public int IdAccion { get; set; }
    
        public virtual Accion Accion { get; set; }
        public virtual Pantalla Pantalla { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
