CREATE TABLE [dbo].[Indicador] (
    [IdIndicador]                    INT            IDENTITY (1, 1) NOT NULL,
    [Codigo]                         VARCHAR (30)   NULL,
    [Nombre]                         VARCHAR (500)  NULL,
    [IdTipoIndicador]                INT            NOT NULL,
    [IdClasificacionIndicador]       INT            NOT NULL,
    [IdGrupoIndicador]               INT            NOT NULL,
    [IdGraficoInforme]               INT            NULL,
    [Descripcion]                    VARCHAR (2000) NULL,
    [CantidadVariableDato]           INT            NULL,
    [CantidadCategoriaDesagregacion] INT            NULL,
    [IdUnidadEstudio]                INT            NULL,
    [IdTipoMedida]                   INT            NOT NULL,
    [IdFrecuenciaEnvio]              INT            NOT NULL,
    [Interno]                        BIT            NULL,
    [Solicitud]                      BIT            NULL,
    [Fuente]                         VARCHAR (300)  NULL,
    [Nota]                           VARCHAR (3000) NULL,
    [FechaCreacion]                  DATETIME       CONSTRAINT [DF_Indicador_FechaCreacion] DEFAULT (getdate()) NOT NULL,
    [UsuarioCreacion]                VARCHAR (100)  NOT NULL,
    [FechaModificacion]              DATETIME       NULL,
    [UsuarioModificacion]            VARCHAR (100)  NULL,
    [VisualizaSigitel]               BIT            NOT NULL,
    [IdEstadoRegistro]               INT            NOT NULL,
    CONSTRAINT [PK_ParametrosIndicador] PRIMARY KEY CLUSTERED ([IdIndicador] ASC),
    CONSTRAINT [FK_Indicador_ClasificacionIndicador] FOREIGN KEY ([IdClasificacionIndicador]) REFERENCES [dbo].[ClasificacionIndicador] ([IdClasificacionIndicador]),
    CONSTRAINT [FK_Indicador_EstadoRegistro] FOREIGN KEY ([IdEstadoRegistro]) REFERENCES [dbo].[EstadoRegistro] ([IdEstadoRegistro]),
    CONSTRAINT [FK_Indicador_FrecuenciaEnvio] FOREIGN KEY ([IdFrecuenciaEnvio]) REFERENCES [dbo].[FrecuenciaEnvio] ([IdFrecuenciaEnvio]),
    CONSTRAINT [FK_Indicador_GraficoInforme] FOREIGN KEY ([IdGraficoInforme]) REFERENCES [dbo].[GraficoInforme] ([IdGraficoInforme]),
    CONSTRAINT [FK_Indicador_GrupoIndicador] FOREIGN KEY ([IdGrupoIndicador]) REFERENCES [dbo].[GrupoIndicador] ([IdGrupoIndicador]),
    CONSTRAINT [FK_Indicador_TipoMedida] FOREIGN KEY ([IdTipoMedida]) REFERENCES [dbo].[TipoMedida] ([IdTipoMedida]),
    CONSTRAINT [FK_Indicador_UnidadEstudio] FOREIGN KEY ([IdUnidadEstudio]) REFERENCES [dbo].[UnidadEstudio] ([IdUnidadEstudio]),
    CONSTRAINT [FK_ParametrosIndicador_TipoIndicador] FOREIGN KEY ([IdTipoIndicador]) REFERENCES [dbo].[TipoIndicador] ([IdTipoIndicador])
);

