CREATE TABLE [dbo].[Indicador] (
    [IdIndicador]                     INT            IDENTITY (1, 1) NOT NULL,
    [Codigo]                          VARCHAR (30)   NULL,
    [Nombre]                          VARCHAR (350)  NULL,
    [IdTipoIndicador]                 INT            NOT NULL,
    [IdClasificacion]                 INT            NOT NULL,
    [IdGrupo]                         INT            NOT NULL,
    [Descripcion]                     VARCHAR (2000) NULL,
    [CantidadVariableDato]            INT            NULL,
    [CantidadCategoriasDesagregacion] INT            NULL,
    [IdUnidadEstudio]                 INT            NULL,
    [IdTipoMedida]                    INT            NOT NULL,
    [IdFrecuencia]                    INT            NOT NULL,
    [Interno]                         BIT            NULL,
    [Solicitud]                       BIT            NULL,
    [Fuente]                          VARCHAR (300)  NULL,
    [Notas]                           VARCHAR (3000) NULL,
    [FechaCreacion]                   DATETIME       CONSTRAINT [DF_Indicador_FechaCreacion] DEFAULT (getdate()) NOT NULL,
    [UsuarioCreacion]                 VARCHAR (100)  NOT NULL,
    [FechaModificacion]               DATETIME       NULL,
    [UsuarioModificacion]             VARCHAR (100)  NULL,
    [VisualizaSigitel]                BIT            NOT NULL,
    [IdEstado]                        INT            NOT NULL,
    CONSTRAINT [PK_ParametrosIndicadores] PRIMARY KEY CLUSTERED ([IdIndicador] ASC),
    CONSTRAINT [FK_Indicador_ClasificacionIndicadores] FOREIGN KEY ([IdClasificacion]) REFERENCES [dbo].[ClasificacionIndicadores] ([IdClasificacion]),
    CONSTRAINT [FK_Indicador_EstadoRegistro] FOREIGN KEY ([IdEstado]) REFERENCES [dbo].[EstadoRegistro] ([IdEstado]),
    CONSTRAINT [FK_Indicador_FrecuenciaEnvio] FOREIGN KEY ([IdFrecuencia]) REFERENCES [dbo].[FrecuenciaEnvio] ([IdFrecuencia]),
    CONSTRAINT [FK_Indicador_GrupoIndicadores] FOREIGN KEY ([IdGrupo]) REFERENCES [dbo].[GrupoIndicadores] ([IdGrupo]),
    CONSTRAINT [FK_Indicador_TipoMedida] FOREIGN KEY ([IdTipoMedida]) REFERENCES [dbo].[TipoMedida] ([IdMedida]),
    CONSTRAINT [FK_Indicador_UnidadEstudio] FOREIGN KEY ([IdUnidadEstudio]) REFERENCES [dbo].[UnidadEstudio] ([IdUnidad]),
    CONSTRAINT [FK_ParametrosIndicadores_TipoIndicadores] FOREIGN KEY ([IdTipoIndicador]) REFERENCES [dbo].[TipoIndicadores] ([IdTipoIdicador])
);



