CREATE TABLE [dbo].[Indicador] (
    [idIndicador]                     INT            IDENTITY (1, 1) NOT NULL,
    [Codigo]                          VARCHAR (30)   NULL,
    [Nombre]                          VARCHAR (350)  NULL,
    [IdTipoIndicador]                 INT            NOT NULL,
    [IdClasificacion]                 INT            NOT NULL,
    [idGrupo]                         INT            NOT NULL,
    [Descripcion]                     VARCHAR (2000) NULL,
    [CantidadVariableDato]            INT            NULL,
    [CantidadCategoriasDesagregacion] INT            NULL,
    [IdUnidadEstudio]                 INT            NULL,
    [idTipoMedida]                    INT            NOT NULL,
    [IdFrecuencia]                    INT            NOT NULL,
    [Interno]                         BIT            NULL,
    [Solicitud]                       BIT            NOT NULL,
    [Fuente]                          VARCHAR (300)  NULL,
    [Notas]                           VARCHAR (3000) NULL,
    [FechaCreacion]                   DATETIME       CONSTRAINT [DF_Indicador_FechaCreacion] DEFAULT (getdate()) NOT NULL,
    [UsuarioCreacion]                 VARCHAR (100)  NOT NULL,
    [FechaModificacion]               DATETIME       NULL,
    [UsuarioModificacion]             VARCHAR (100)  NULL,
    [VisualizaSigitel]                BIT            NOT NULL,
    [idEstado]                        INT            NOT NULL,
    CONSTRAINT [PK_ParametrosIndicadores] PRIMARY KEY CLUSTERED ([idIndicador] ASC),
    CONSTRAINT [FK_Indicador_ClasificacionIndicadores] FOREIGN KEY ([IdClasificacion]) REFERENCES [dbo].[ClasificacionIndicadores] ([idClasificacion]),
    CONSTRAINT [FK_Indicador_EstadoRegistro] FOREIGN KEY ([idEstado]) REFERENCES [dbo].[EstadoRegistro] ([idEstado]),
    CONSTRAINT [FK_Indicador_FrecuenciaEnvio] FOREIGN KEY ([IdFrecuencia]) REFERENCES [dbo].[FrecuenciaEnvio] ([idFrecuencia]),
    CONSTRAINT [FK_Indicador_GrupoIndicadores] FOREIGN KEY ([idGrupo]) REFERENCES [dbo].[GrupoIndicadores] ([idGrupo]),
    CONSTRAINT [FK_Indicador_TipoMedida] FOREIGN KEY ([idTipoMedida]) REFERENCES [dbo].[TipoMedida] ([idMedida]),
    CONSTRAINT [FK_Indicador_UnidadEstudio] FOREIGN KEY ([IdUnidadEstudio]) REFERENCES [dbo].[UnidadEstudio] ([idUnidad]),
    CONSTRAINT [FK_ParametrosIndicadores_TipoIndicadores] FOREIGN KEY ([IdTipoIndicador]) REFERENCES [dbo].[TipoIndicadores] ([IdTipoIdicador])
);

