//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraSync
    {
        public System.Guid IdProcess { get; set; }
        public System.DateTime DateSync { get; set; }
        public string Status { get; set; }
        public int RowsInsert { get; set; }
        public int RowsUpdate { get; set; }
        public string Error { get; set; }
    }
}
