//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordenadasArchivoMif
    {
        public int IdCoordenadasArchivoMif { get; set; }
        public int IdArchivoMif { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<int> Region { get; set; }
    
        public virtual ArchivoMif ArchivoMif { get; set; }
    }
}
