//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criterio()
        {
            this.ConstructorCriterio = new HashSet<ConstructorCriterio>();
        }
    
        public string IdCriterio { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public string DescCriterio { get; set; }
        public Nullable<byte> Borrado { get; set; }
        public string IdIndicador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructorCriterio> ConstructorCriterio { get; set; }
        public virtual Indicador Indicador { get; set; }
        public virtual Direccion Direccion { get; set; }
    }
}
