//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleArchivoTelevisionDigitalCsv
    {
        public int idDetalle { get; set; }
        public Nullable<int> IdArchivoCsv { get; set; }
        public Nullable<System.DateTime> Tiempo { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public string NombreSistema { get; set; }
        public Nullable<decimal> ISDBT { get; set; }
        public Nullable<int> Acimut { get; set; }
        public string Logitud { get; set; }
        public string Latitude { get; set; }
        public string ArchInfo { get; set; }
    
        public virtual ArchivoTelevisionDigitalCsv ArchivoTelevisionDigitalCsv { get; set; }
    }
}
