//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAgrupacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleAgrupacion()
        {
            this.ConstructorCriterioDetalleAgrupacion = new HashSet<ConstructorCriterioDetalleAgrupacion>();
        }
    
        public int IdDetalleAgrupacion { get; set; }
        public string IdOperador { get; set; }
        public int IdAgrupacion { get; set; }
        public string DescDetalleAgrupacion { get; set; }
        public byte Borrado { get; set; }
        public byte[] DescHexa { get; set; }
    
        public virtual Agrupacion Agrupacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructorCriterioDetalleAgrupacion> ConstructorCriterioDetalleAgrupacion { get; set; }
        public virtual Operador Operador { get; set; }
    }
}
