//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorExterno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndicadorExterno()
        {
            this.DetalleIndicadorCruzado = new HashSet<DetalleIndicadorCruzado>();
            this.RegistroIndicadorExterno = new HashSet<RegistroIndicadorExterno>();
        }
    
        public string IdIndicadorExterno { get; set; }
        public int IdFuenteExterna { get; set; }
        public Nullable<int> IdTipoValor { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public byte Borrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleIndicadorCruzado> DetalleIndicadorCruzado { get; set; }
        public virtual FuenteExterna FuenteExterna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroIndicadorExterno> RegistroIndicadorExterno { get; set; }
        public virtual TipoValor TipoValor { get; set; }
    }
}
