//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogFormulas
    {
        public int Idlog { get; set; }
        public string Indicador { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Usuario { get; set; }
        public string FormulaAntiguaCumpli { get; set; }
        public string FormulaNuevaCumpli { get; set; }
        public string FormulaAntiguaPor { get; set; }
        public string FormulaNuevaPor { get; set; }
        public string TipoAccion { get; set; }
    }
}
