//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudIndicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudIndicador()
        {
            this.SolicitudConstructor = new HashSet<SolicitudConstructor>();
        }
    
        public System.Guid IdSolicitudIndicador { get; set; }
        public int IdFrecuencia { get; set; }
        public int IdServicio { get; set; }
        public int IdDireccion { get; set; }
        public string DescFormulario { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public byte Activo { get; set; }
        public byte Borrado { get; set; }
        public System.DateTime FechaBaseParaCrearExcel { get; set; }
        public int FormularioWeb { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Frecuencia Frecuencia { get; set; }
        public virtual Servicio Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudConstructor> SolicitudConstructor { get; set; }
    }
}
