//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioLogin
    {
        public int IdUsuario { get; set; }
        public bool PrimerLogueo { get; set; }
        public byte Intentos { get; set; }
        public Nullable<System.DateTime> UltimoLogueoFallido { get; set; }
        public Nullable<System.DateTime> UltimoLogueoExitoso { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
