CREATE PROCEDURE [dbo].[pa_RptTiposIndicadorPorServicio] 
	--PARÁMETROS
	-- LISTA DE CÓDIGOS DE SERVICIOS SEPARADOS POR COMAS (,)
	@PSERVICIOS VARCHAR(MAX) = '', 
	-- LISTA DE CÓDIGOS DE TIPOS DE INDICADOR SEPARADOS POR COMAS (,)
	@PTIPOSINDICADOR  VARCHAR(MAX) = ''        
AS
BEGIN
	SET NOCOUNT ON;

	--VERIFICAR PARÁMETROS
	SET @PSERVICIOS = ISNULL(@PSERVICIOS, '')
	SET @PTIPOSINDICADOR = ISNULL(@PTIPOSINDICADOR, '')
		
    SELECT LTRIM(S.DESSERVICIO) AS SERVICIO, LTRIM(TI.DESTIPOIND) AS TIPOINDICADOR
	FROM DBO.TIPOINDICADOR AS TI WITH (NOLOCK)
	INNER JOIN DBO.TIPOINDICADORSERVICIO AS TIS WITH (NOLOCK)
	ON TIS.IDTIPOIND = TI.IDTIPOIND
	AND TIS.BORRADO = 0
	INNER JOIN DBO.SERVICIO AS S WITH (NOLOCK)
	ON S.IDSERVICIO = TIS.IDSERVICIO AND S.BORRADO = 0
	WHERE
	(1=(CASE WHEN LEN(@PSERVICIOS)<1 THEN 1 ELSE 0 END) OR TIS.IDSERVICIO IN (SELECT VALUE FROM DBO.FN_SPLIT (@PSERVICIOS,',')))
	AND
	(1=(CASE WHEN LEN(@PTIPOSINDICADOR)<1 THEN 1 ELSE 0 END) OR TIS.IDTIPOIND IN (SELECT VALUE FROM DBO.FN_SPLIT (@PTIPOSINDICADOR,',')))
	ORDER BY S.DESSERVICIO, TI.DESTIPOIND

END