


-- ============================================================================================
-- Author:		<Adrián Jiménez>
-- Create date: <06052015>
-- Description:	<Provee información para el reporte denominado Indicadores por Operador>
-- ============================================================================================
CREATE PROCEDURE [dbo].[pa_RptIndicadoresPorOperador] 
	--PARÁMETROS
	-- LISTA DE CÓDIGOS DE OPERADORES SEPARADOS POR COMAS (,)
	@pOperadores VARCHAR(MAX) = '', 
	-- LISTA DE CÓDIGOS DE SERVICIOS SEPARADOS POR COMAS (,)
	@pServicios VARCHAR(MAX) = '', 
	-- LISTA DE DIRECCIONES (Mercados/Calidad)  SEPARADAS POR COMAS (,)
	@pDirecciones  VARCHAR(MAX) = ''        
AS
BEGIN
	SET NOCOUNT ON;

	--VERIFICAR PARÁMETROS
	SET @pOperadores = ISNULL(@pOperadores, '')
	SET @pServicios = ISNULL(@pServicios, '')
	SET @pDirecciones = ISNULL(@pDirecciones, '')

	SELECT OP.IDOPERADOR,OP.NOMBREOPERADOR,S.IDSERVICIO,S.DESSERVICIO,I.IDINDICADOR,I.NOMBREINDICADOR,
	i.DESCINDICADOR, ti.DESTIPOIND as DESCTIPOINDICADOR, D.NOMBRE AS DIRECCION 
	FROM dbo.OPERADOR as OP with(nolock)
	INNER JOIN dbo.SERVICIOOPERADOR as SO with(nolock)
	ON op.IDOPERADOR = SO.IDOPERADOR AND SO.BORRADO = 0 
	inner join DBO.SERVICIO AS S WITH(NOLOCK)
	ON SO.IDESERVICIO = S.IDSERVICIO AND S.BORRADO = 0
	INNER JOIN DBO.SERVICIOINDICADOR AS SI WITH(NOLOCK)
	ON SI.IDSERVICIO = S.IDSERVICIO AND S.BORRADO = 0 
	INNER JOIN DBO.INDICADOR AS I WITH(NOLOCK)
	ON SI.IDINDICADOR = I.IDINDICADOR 
	INNER JOIN DBO.TIPOINDICADOR AS TI WITH(NOLOCK)
	ON I.IDTIPOIND = TI.IDTIPOIND AND TI.BORRADO = 0
	INNER JOIN DBO.INDICADORDIRECCION AS ID WITH(NOLOCK)
	ON I.IDINDICADOR = ID.IDINDICADOR
	INNER JOIN DBO.DIRECCION AS D WITH(NOLOCK)
	ON ID.IDDIRECCION = D.IDDIRECCION
	WHERE
	(1=(CASE WHEN LEN(@pOperadores)<1 THEN 1 ELSE 0 END) OR SO.IDOPERADOR IN (SELECT VALUE FROM DBO.FN_SPLIT (@pOperadores,',')))
	AND
	(1=(CASE WHEN LEN(@pServicios)<1 THEN 1 ELSE 0 END) OR SO.IDESERVICIO IN (SELECT VALUE FROM DBO.FN_SPLIT (@pServicios,',')))
	AND
	(1=(CASE WHEN LEN(@pDirecciones)<1 THEN 1 ELSE 0 END) OR ID.IDDIRECCION IN (SELECT VALUE FROM DBO.FN_SPLIT (@pDirecciones,',')))
	ORDER BY OP.NOMBREOPERADOR,S.DESSERVICIO,i.NOMBREINDICADOR
	
END