CREATE PROCEDURE [dbo].[pa_RptIndicadoresPorServicio] 
	--PARÁMETROS
	-- LISTA DE CÓDIGOS DE SERVICIOS SEPARADOS POR COMAS (,)
	@pServicios VARCHAR(MAX) = '', 
	-- LISTA DE CÓDIGOS DE INDICADORES SEPARADOS POR COMAS (,)
	@pIndicadores  VARCHAR(MAX) = ''        
AS
BEGIN
	SET NOCOUNT ON;

	--VERIFICAR PARÁMETROS
	SET @pServicios = ISNULL(@pServicios, '')
	SET @pIndicadores = ISNULL(@pIndicadores, '')

	SELECT S.IDSERVICIO, S.DESSERVICIO AS DESCSERVICIO, i.IDINDICADOR as IDINDICADOR, i.NOMBREINDICADOR as NOMINDICADOR,
	i.DESCINDICADOR, ti.DESTIPOIND as DESCTIPOINDICADOR, D.NOMBRE AS DIRECCION
	FROM DBO.SERVICIO AS S WITH(NOLOCK)
	INNER JOIN DBO.SERVICIOINDICADOR AS SI WITH(NOLOCK)
	ON SI.IDSERVICIO = S.IDSERVICIO AND S.BORRADO = 0 
	INNER JOIN DBO.INDICADOR AS I WITH(NOLOCK)
	ON SI.IDINDICADOR = I.IDINDICADOR 
	INNER JOIN DBO.TIPOINDICADOR AS TI WITH(NOLOCK)
	ON I.IDTIPOIND = TI.IDTIPOIND AND TI.BORRADO = 0
	INNER JOIN DBO.INDICADORDIRECCION AS ID WITH(NOLOCK)
	ON I.IDINDICADOR = ID.IDINDICADOR
	INNER JOIN DBO.DIRECCION AS D WITH(NOLOCK)
	ON ID.IDDIRECCION = D.IDDIRECCION
	WHERE
	(1=(CASE WHEN LEN(@pServicios)<1 THEN 1 ELSE 0 END) OR si.IDSERVICIO IN (SELECT VALUE FROM DBO.FN_SPLIT (@pServicios,',')))
	AND
	(1=(CASE WHEN LEN(@pIndicadores)<1 THEN 1 ELSE 0 END) OR si.IDINDICADOR IN (SELECT VALUE FROM DBO.FN_SPLIT (@pIndicadores,',')))
	ORDER BY S.DESSERVICIO, i.NOMBREINDICADOR
	
END