//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SUTEL.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar Archivo.
        /// </summary>
        public static string btnCargaArchivo {
            get {
                return ResourceManager.GetString("btnCargaArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga de Registro.
        /// </summary>
        public static string btnCargaRegsitro {
            get {
                return ResourceManager.GetString("btnCargaRegsitro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancela la acción actual..
        /// </summary>
        public static string btnTooltipCancelar {
            get {
                return ResourceManager.GetString("btnTooltipCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga la plantilla de registro de indicadores externos y guarda los datos que contenga..
        /// </summary>
        public static string btnTooltipCargaAutomatica {
            get {
                return ResourceManager.GetString("btnTooltipCargaAutomatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica el dato seleccionado..
        /// </summary>
        public static string btnTooltipEditar {
            get {
                return ResourceManager.GetString("btnTooltipEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimina el dato seleccionado..
        /// </summary>
        public static string btnTooltipEliminar {
            get {
                return ResourceManager.GetString("btnTooltipEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga la plantilla del registro de indicadores externos en formato .xlsx para hacer una carga automática..
        /// </summary>
        public static string btnTooltipGenerarPlantilla {
            get {
                return ResourceManager.GetString("btnTooltipGenerarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarda un nuevo dato..
        /// </summary>
        public static string btnTooltipGuardar {
            get {
                return ResourceManager.GetString("btnTooltipGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea un registro nuevo..
        /// </summary>
        public static string btnTooltipNuevo {
            get {
                return ResourceManager.GetString("btnTooltipNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previsualización de la plantilla de registro de indicadores externos..
        /// </summary>
        public static string btnToolTipPrevisualizacionPlantilla {
            get {
                return ResourceManager.GetString("btnToolTipPrevisualizacionPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloq Mayús está activado.
        /// </summary>
        public static string CapsLock {
            get {
                return ResourceManager.GetString("CapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija su idioma de preferencia.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string Disactive {
            get {
                return ResourceManager.GetString("Disactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales Inválidas..
        /// </summary>
        public static string InvalidCredencials {
            get {
                return ResourceManager.GetString("InvalidCredencials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos en la tabla.
        /// </summary>
        public static string noDataInTableMsg {
            get {
                return ResourceManager.GetString("noDataInTableMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación fue exitosa..
        /// </summary>
        public static string OperacionExitosa {
            get {
                return ResourceManager.GetString("OperacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado usuario: El excel que corresponde a la solicitud marcada solo puede cargarse a nuestra sistema una única vez. Por favor, revise el documento antes de subirlo..
        /// </summary>
        public static string RegistroIndicador_msjUsuarioCargaExel {
            get {
                return ResourceManager.GetString("RegistroIndicador_msjUsuarioCargaExel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene permisos para consultar..
        /// </summary>
        public static string SinPermisosIndex {
            get {
                return ResourceManager.GetString("SinPermisosIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron datos.
        /// </summary>
        public static string TablaVacia {
            get {
                return ResourceManager.GetString("TablaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola yo soy un titulo en español.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
