using GB.SIMEF.Entities;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Sprint-1/cambios-Formulario
using GB.SIMEF.Resources;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Sprint-1/FormularioWEB
using System;
using System.Collections.Generic;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Sprint-1/cambios-Formulario
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
using System.Data.SqlClient;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Sprint-1/FormularioWEB
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GB.SIMEF.DAL
{
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Sprint-1/cambios-Formulario
    public class FrecuenciaEnvioDAL : BitacoraDAL
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
    public class FrecuenciaEnvioDAL: BitacoraDAL
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Sprint-1/FormularioWEB
    {
        private SIMEFContext db;

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Sprint-1/cambios-Formulario
        /// <summary>
        /// 23/08/2022
        /// José Navarro Acuña
        /// Función que retorna todos las frecuencias de envio registradas en estado activo.
        /// Se puede filtrar por el ID del objecto
        /// </summary>
        /// <returns></returns>
        public List<FrecuenciaEnvio> ObtenerDatos(FrecuenciaEnvio pFrecuenciaEnvio)
        {
            List<FrecuenciaEnvio> lista = new List<FrecuenciaEnvio>();

        #region Metodos Consulta Base de Datos
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Sprint-1/FormularioWEB

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Sprint-1/cambios-Formulario
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
        public List<FrecuenciaEnvio> ObtenerDatos(FrecuenciaEnvio objFrecuenciaEnvio)
        {
            List<FrecuenciaEnvio> ListaFrecuenciaEnvios = new List<FrecuenciaEnvio>();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Sprint-1/FormularioWEB
            using (db = new SIMEFContext())
            {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Sprint-1/cambios-Formulario
                if (pFrecuenciaEnvio.idFrecuencia != 0)
                {
                    lista = db.FrecuenciaEnvio.Where(x => x.idFrecuencia == pFrecuenciaEnvio.idFrecuencia && x.Estado == true).ToList();
                }
                else
                {
                    lista = db.FrecuenciaEnvio.Where(x => x.Estado == true).ToList();
                }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
                ListaFrecuenciaEnvios = db.Database.SqlQuery<FrecuenciaEnvio>
                    ("execute spObtenerFrecuenciasEnvio @idFrecuencia",
                    new SqlParameter("@idFrecuencia", objFrecuenciaEnvio.idFrecuencia)
                    ).ToList();
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Sprint-1/FormularioWEB
            }
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Sprint-1/cambios-Formulario

            lista = lista.Select(x => new FrecuenciaEnvio()
            {
                id = Utilidades.Encriptar(x.idFrecuencia.ToString()),
                Nombre = x.Nombre,
                CantidadDias = x.CantidadDias,
                Estado = x.Estado
            }).ToList();
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
            return ListaFrecuenciaEnvios;
        }
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Sprint-1/FormularioWEB

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Sprint-1/cambios-Formulario
            return lista;
        }
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
        #endregion
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Sprint-1/FormularioWEB
    }
}
