//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SUTEL.Resources.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los archivos elegidos exceden la capacidad de tamaño permitida. La capacidad máxima es de 30 MB..
        /// </summary>
        public static string CapacidadMaximaExcedida {
            get {
                return ResourceManager.GetString("CapacidadMaximaExcedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso de creación de .
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un problema en la carga de la plantilla.
        /// </summary>
        public static string ErrorCarga {
            get {
                return ResourceManager.GetString("ErrorCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información se actualizó con éxito..
        /// </summary>
        public static string ExitoEditar {
            get {
                return ResourceManager.GetString("ExitoEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información se ha Eliminado con éxito..
        /// </summary>
        public static string ExitoEliminar {
            get {
                return ResourceManager.GetString("ExitoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro se insertó correctamente..
        /// </summary>
        public static string ExitoInsertar {
            get {
                return ResourceManager.GetString("ExitoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el Operador.
        /// </summary>
        public static string MensajeSeleccionesOperador_serviciosOperador {
            get {
                return ResourceManager.GetString("MensajeSeleccionesOperador_serviciosOperador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota: Para verificar que el proceso de inserción y reemplazo hayan finalizado genere el Reporte de bitácora..
        /// </summary>
        public static string NotaVerificarFinalizacionCarga {
            get {
                return ResourceManager.GetString("NotaVerificarFinalizacionCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificacion correcta.
        /// </summary>
        public static string Notificacion {
            get {
                return ResourceManager.GetString("Notificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea cargar los archivos?.
        /// </summary>
        public static string PreguntaConfirmarCarga {
            get {
                return ResourceManager.GetString("PreguntaConfirmarCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ingresar registros duplicados..
        /// </summary>
        public static string RegistroCodigoDuplicado {
            get {
                return ResourceManager.GetString("RegistroCodigoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ingresar registros duplicados..
        /// </summary>
        public static string RegistroDescripcionDuplicado {
            get {
                return ResourceManager.GetString("RegistroDescripcionDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible ingresar registros duplicados..
        /// </summary>
        public static string RegistroDuplicado {
            get {
                return ResourceManager.GetString("RegistroDuplicado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El registro no se puede eliminar porque está en uso..
        /// </summary>
        public static string RegistroNoSePuedeEliminar
        {
            get
            {
                return ResourceManager.GetString("RegistroNoSePuedeEliminar", resourceCulture);
            }
        }
        public static string RegistroNoSePuedeEditar
        {
            get
            {
                return ResourceManager.GetString("RegistroNoSePuedeEditar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar minimo un servicio.
        /// </summary>
        public static string RegistroOperadorServicio {
            get {
                return ResourceManager.GetString("RegistroOperadorServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se insertó {0} registros..
        /// </summary>
        public static string RegistrosInsertados {
            get {
                return ResourceManager.GetString("RegistrosInsertados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede cargar archivos CSV y MIF.
        /// </summary>
        public static string TiposPermitidos {
            get {
                return ResourceManager.GetString("TiposPermitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga de los archivos del sistema de monitoreo y polígonos mapinfo.
        /// </summary>
        public static string TituloPantallaEspectro {
            get {
                return ResourceManager.GetString("TituloPantallaEspectro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado de carga de archivos del sistema de monitoreo y polígonos mapinfo.
        /// </summary>
        public static string TituloPantallaResultadoDeCargaArchivos {
            get {
                return ResourceManager.GetString("TituloPantallaResultadoDeCargaArchivos", resourceCulture);
            }
        }
    }
}
