//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EtiquetasViewReglasValidacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EtiquetasViewReglasValidacion() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SIMEF.Resources.EtiquetasViewReglasValidacion", typeof(EtiquetasViewReglasValidacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atributos Válidos.
        /// </summary>
        public static string AtributosValidos {
            get {
                return ResourceManager.GetString("AtributosValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría Actualizable.
        /// </summary>
        public static string CategoriaActualizable {
            get {
                return ResourceManager.GetString("CategoriaActualizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría ID.
        /// </summary>
        public static string CategoriaID {
            get {
                return ResourceManager.GetString("CategoriaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clonar Reglas de Validación.
        /// </summary>
        public static string Clonar {
            get {
                return ResourceManager.GetString("Clonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variable Dato de Comparación.
        /// </summary>
        public static string Comparacion {
            get {
                return ResourceManager.GetString("Comparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Reglas de Validación.
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Reglas de Validación.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador de Comparación.
        /// </summary>
        public static string IndicadorComparacion {
            get {
                return ResourceManager.GetString("IndicadorComparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador de Salida.
        /// </summary>
        public static string IndicadorSalida {
            get {
                return ResourceManager.GetString("IndicadorSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string LabelCodigo {
            get {
                return ResourceManager.GetString("LabelCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string LabelDescripcion {
            get {
                return ResourceManager.GetString("LabelDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicador a Aplicar.
        /// </summary>
        public static string LabelIndicador {
            get {
                return ResourceManager.GetString("LabelIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string LabelNombre {
            get {
                return ResourceManager.GetString("LabelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operador.
        /// </summary>
        public static string Operador {
            get {
                return ResourceManager.GetString("Operador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglas de Validación.
        /// </summary>
        public static string ReglasValidacion {
            get {
                return ResourceManager.GetString("ReglasValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Regla.
        /// </summary>
        public static string TipoRegla {
            get {
                return ResourceManager.GetString("TipoRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Constante.
        /// </summary>
        public static string ValorConstante {
            get {
                return ResourceManager.GetString("ValorConstante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variable Dato.
        /// </summary>
        public static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualización Reglas de Validación.
        /// </summary>
        public static string VIsualiza {
            get {
                return ResourceManager.GetString("VIsualiza", resourceCulture);
            }
        }
    }
}
