//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EtiquetasViewIndicadorFonatel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EtiquetasViewIndicadorFonatel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SIMEF.Resources.EtiquetasViewIndicadorFonatel", typeof(EtiquetasViewIndicadorFonatel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string CrearCategoria_LabelCategoriaIndicador {
            get {
                return ResourceManager.GetString("CrearCategoria_LabelCategoriaIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string CrearCategoria_LabelDetalleIndicador {
            get {
                return ResourceManager.GetString("CrearCategoria_LabelDetalleIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Categorías de Desagregación.
        /// </summary>
        public static string CrearIndicador_LabelCantidadCategoriaIndicador {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelCantidadCategoriaIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Variables Dato.
        /// </summary>
        public static string CrearIndicador_LabelCantidadVariableDatosIndicador {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelCantidadVariableDatosIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificación.
        /// </summary>
        public static string CrearIndicador_LabelClasificacion {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string CrearIndicador_LabelCodigo {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string CrearIndicador_LabelDescripcion {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia.
        /// </summary>
        public static string CrearIndicador_LabelFrecuencias {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelFrecuencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente.
        /// </summary>
        public static string CrearIndicador_LabelFuenteIndicador {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelFuenteIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string CrearIndicador_LabelGrupo {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CrearIndicador_LabelNombre {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        public static string CrearIndicador_LabelNotas {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.
        /// </summary>
        public static string CrearIndicador_LabelSolicitud {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo indicador.
        /// </summary>
        public static string CrearIndicador_LabelTipo {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Medida.
        /// </summary>
        public static string CrearIndicador_LabelTipoMedida {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelTipoMedida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de Estudio.
        /// </summary>
        public static string CrearIndicador_LabelUnidadEstudio {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelUnidadEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso.
        /// </summary>
        public static string CrearIndicador_LabelUsoIndicador {
            get {
                return ResourceManager.GetString("CrearIndicador_LabelUsoIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción de categoria.
        /// </summary>
        public static string CrearIndicador_TextAreaDescripcionPlaceholder {
            get {
                return ResourceManager.GetString("CrearIndicador_TextAreaDescripcionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string CrearVariable_LabelDescripcionVariable {
            get {
                return ResourceManager.GetString("CrearVariable_LabelDescripcionVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CrearVariable_LabelNombreVariable {
            get {
                return ResourceManager.GetString("CrearVariable_LabelNombreVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        public static string CrearVariable_LabelVariableIndicador {
            get {
                return ResourceManager.GetString("CrearVariable_LabelVariableIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías.
        /// </summary>
        public static string LabelStepperCategorias {
            get {
                return ResourceManager.GetString("LabelStepperCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador.
        /// </summary>
        public static string LabelStepperIndicador {
            get {
                return ResourceManager.GetString("LabelStepperIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string LabelStepperVariables {
            get {
                return ResourceManager.GetString("LabelStepperVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Categoría.
        /// </summary>
        public static string TituloAgregarCategoria {
            get {
                return ResourceManager.GetString("TituloAgregarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Indicador.
        /// </summary>
        public static string TituloCrearIndicador {
            get {
                return ResourceManager.GetString("TituloCrearIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Variable Dato.
        /// </summary>
        public static string TituloCrearVariable {
            get {
                return ResourceManager.GetString("TituloCrearVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores.
        /// </summary>
        public static string TituloIndex {
            get {
                return ResourceManager.GetString("TituloIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Indicador.
        /// </summary>
        public static string TituloModalGrupoIndicador {
            get {
                return ResourceManager.GetString("TituloModalGrupoIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Indicador.
        /// </summary>
        public static string TituloModalTipoIndicador {
            get {
                return ResourceManager.GetString("TituloModalTipoIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de Estudio.
        /// </summary>
        public static string TituloModalUnidadEstudio {
            get {
                return ResourceManager.GetString("TituloModalUnidadEstudio", resourceCulture);
            }
        }
    }
}
