//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Etiquetas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Etiquetas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SIMEF.Resources.Etiquetas", typeof(Etiquetas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Bitácora.
        /// </summary>
        public static string Bitacora {
            get {
                return ResourceManager.GetString("Bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrás.
        /// </summary>
        public static string BotonAtras {
            get {
                return ResourceManager.GetString("BotonAtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string BotonBuscar {
            get {
                return ResourceManager.GetString("BotonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BotonCancelar {
            get {
                return ResourceManager.GetString("BotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        public static string BotonCargar {
            get {
                return ResourceManager.GetString("BotonCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string BotonCrear {
            get {
                return ResourceManager.GetString("BotonCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string BotonDescarga {
            get {
                return ResourceManager.GetString("BotonDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar.
        /// </summary>
        public static string BotonFinalizar {
            get {
                return ResourceManager.GetString("BotonFinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado parcial.
        /// </summary>
        public static string BotonGuardadoParcial {
            get {
                return ResourceManager.GetString("BotonGuardadoParcial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string BotonGuardar {
            get {
                return ResourceManager.GetString("BotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string BotonSiguiente {
            get {
                return ResourceManager.GetString("BotonSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validar.
        /// </summary>
        public static string BotonValidar {
            get {
                return ResourceManager.GetString("BotonValidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string BotonVisualizar {
            get {
                return ResourceManager.GetString("BotonVisualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo requerido.
        /// </summary>
        public static string CampoRequerido {
            get {
                return ResourceManager.GetString("CampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Excel.
        /// </summary>
        public static string DescargaExcel {
            get {
                return ResourceManager.GetString("DescargaExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Categoría Desagregación.
        /// </summary>
        public static string DetalleCategorias {
            get {
                return ResourceManager.GetString("DetalleCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario Web.
        /// </summary>
        public static string Formulario {
            get {
                return ResourceManager.GetString("Formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrecuenciaEnvio.
        /// </summary>
        public static string Frecuencia {
            get {
                return ResourceManager.GetString("Frecuencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador.
        /// </summary>
        public static string Indicador {
            get {
                return ResourceManager.GetString("Indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string LabelInicio {
            get {
                return ResourceManager.GetString("LabelInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas de Validación.
        /// </summary>
        public static string ReglasValidacion {
            get {
                return ResourceManager.GetString("ReglasValidacion", resourceCulture);
            }
        }
    }
}
