//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EtiquetasViewFormulario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EtiquetasViewFormulario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SIMEF.Resources.EtiquetasViewFormulario", typeof(EtiquetasViewFormulario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Indicadores al Formulario.
        /// </summary>
        public static string AgregarIndicadores {
            get {
                return ResourceManager.GetString("AgregarIndicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de Indicadores.
        /// </summary>
        public static string CantidadIndicadores {
            get {
                return ResourceManager.GetString("CantidadIndicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clonar Formulario Web.
        /// </summary>
        public static string ClonarFormulario {
            get {
                return ResourceManager.GetString("ClonarFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Formulario Web.
        /// </summary>
        public static string CrearFormulario {
            get {
                return ResourceManager.GetString("CrearFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga Formulario Web.
        /// </summary>
        public static string DescargaFormulario {
            get {
                return ResourceManager.GetString("DescargaFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga y Edición de Formulario Web .
        /// </summary>
        public static string EditarFormulario {
            get {
                return ResourceManager.GetString("EditarFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Formulario Web.
        /// </summary>
        public static string EditarFormularioWeb {
            get {
                return ResourceManager.GetString("EditarFormularioWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario.
        /// </summary>
        public static string Formulario {
            get {
                return ResourceManager.GetString("Formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia.
        /// </summary>
        public static string Frecuencia {
            get {
                return ResourceManager.GetString("Frecuencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia de Envío.
        /// </summary>
        public static string FrecuenciaEnvio {
            get {
                return ResourceManager.GetString("FrecuenciaEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuente.
        /// </summary>
        public static string Fuente {
            get {
                return ResourceManager.GetString("Fuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador.
        /// </summary>
        public static string Indicador {
            get {
                return ResourceManager.GetString("Indicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores.
        /// </summary>
        public static string Indicadores {
            get {
                return ResourceManager.GetString("Indicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas de FONATEL para el informante.
        /// </summary>
        public static string NotasEncargado {
            get {
                return ResourceManager.GetString("NotasEncargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.
        /// </summary>
        public static string Solicitud {
            get {
                return ResourceManager.GetString("Solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título de Hoja.
        /// </summary>
        public static string TituloHoja {
            get {
                return ResourceManager.GetString("TituloHoja", resourceCulture);
            }
        }
    }
}
