//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EtiquetasViewRegistroIndicadorFonatel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EtiquetasViewRegistroIndicadorFonatel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SIMEF.Resources.EtiquetasViewRegistroIndicadorFonatel", typeof(EtiquetasViewRegistroIndicadorFonatel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Cantidad de Filas.
        /// </summary>
        public static string CantidadFilas {
            get {
                return ResourceManager.GetString("CantidadFilas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga de Solicitud exitosa.
        /// </summary>
        public static string CargaExitosa {
            get {
                return ResourceManager.GetString("CargaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar plantilla.
        /// </summary>
        public static string CargarPlanilla {
            get {
                return ResourceManager.GetString("CargarPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga y Edición de Formulario.
        /// </summary>
        public static string DescargaPantalla {
            get {
                return ResourceManager.GetString("DescargaPantalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar plantilla.
        /// </summary>
        public static string DescargarPlanilla {
            get {
                return ResourceManager.GetString("DescargarPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviado.
        /// </summary>
        public static string EstadoSolicitudEnviado {
            get {
                return ResourceManager.GetString("EstadoSolicitudEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Proceso .
        /// </summary>
        public static string EstadoSolicitudProceso {
            get {
                return ResourceManager.GetString("EstadoSolicitudProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Fin.
        /// </summary>
        public static string FechaFinal {
            get {
                return ResourceManager.GetString("FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicial.
        /// </summary>
        public static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la Fecha es incorrecto, por favor utilizar el formato año-mes-día.
        /// </summary>
        public static string FormatoFechaIncorrecto {
            get {
                return ResourceManager.GetString("FormatoFechaIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la Variable Dato es incorrecto.
        /// </summary>
        public static string FormatoVariableIncorrecto {
            get {
                return ResourceManager.GetString("FormatoVariableIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llenado Web.
        /// </summary>
        public static string LLenadoWeb {
            get {
                return ResourceManager.GetString("LLenadoWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes Registro.
        /// </summary>
        public static string MesRegistro {
            get {
                return ResourceManager.GetString("MesRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Formulario.
        /// </summary>
        public static string NombreFormulario {
            get {
                return ResourceManager.GetString("NombreFormulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas de FONATEL para el Informante.
        /// </summary>
        public static string NotasEncargado {
            get {
                return ResourceManager.GetString("NotasEncargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas del Informante para FONATEL.
        /// </summary>
        public static string NotasInformante {
            get {
                return ResourceManager.GetString("NotasInformante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha ingresada no cumple con el rango establecido.
        /// </summary>
        public static string RangoFechaIncorrecto {
            get {
                return ResourceManager.GetString("RangoFechaIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Indicador.
        /// </summary>
        public static string RegistroIndicador {
            get {
                return ResourceManager.GetString("RegistroIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema automático.
        /// </summary>
        public static string SistemaAutomatico {
            get {
                return ResourceManager.GetString("SistemaAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.
        /// </summary>
        public static string Solicitud {
            get {
                return ResourceManager.GetString("Solicitud", resourceCulture);
            }
        }
    }
}
