//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SUTEL.Entities.Metadata {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GB.SUTEL.Entities.Metadata.EntityErrors", typeof(EntityErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción de la agrupación no debe superar 600 caracteres..
        /// </summary>
        public static string agrupacionDescripcionTamaño {
            get {
                return ResourceManager.GetString("agrupacionDescripcionTamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo solo puede contener valores alfanuméricos..
        /// </summary>
        public static string Alphanumeric {
            get {
                return ResourceManager.GetString("Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña no coincide..
        /// </summary>
        public static string ClaveNoCoincide {
            get {
                return ResourceManager.GetString("ClaveNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese una dirección de correo válida..
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción no debe ser mayor a los 250 caracteres..
        /// </summary>
        public static string indicadorDescripcionTamanno {
            get {
                return ResourceManager.GetString("indicadorDescripcionTamanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El id no debe ser mayor a los 50 caracteres..
        /// </summary>
        public static string indicadorIdTamanno {
            get {
                return ResourceManager.GetString("indicadorIdTamanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no debe ser mayor a los 250 caracteres..
        /// </summary>
        public static string indicadorNombreTamanno {
            get {
                return ResourceManager.GetString("indicadorNombreTamanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción del Indicador UIT no debe superar 250 caracteres..
        /// </summary>
        public static string indicadorUITDescripcionTamanno {
            get {
                return ResourceManager.GetString("indicadorUITDescripcionTamanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor no debe superar los 9 dígitos..
        /// </summary>
        public static string IntLength {
            get {
                return ResourceManager.GetString("IntLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres Inválidos.
        /// </summary>
        public static string InvalidCharacters {
            get {
                return ResourceManager.GetString("InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato no es correcto, debe contener punto decimal y máximo dos caracteres decimales..
        /// </summary>
        public static string InvalidDoubleFormat {
            get {
                return ResourceManager.GetString("InvalidDoubleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener mínimo 6 caracteres..
        /// </summary>
        public static string PassLength {
            get {
                return ResourceManager.GetString("PassLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-zA-Z0-9-_]+.
        /// </summary>
        public static string RegExCodeValidation {
            get {
                return ResourceManager.GetString("RegExCodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener al menos una letra minúscula, una letra mayúscula, un digito y debe estar entre un rango de 6 a 16 caracteres..
        /// </summary>
        public static string RegExPassword {
            get {
                return ResourceManager.GetString("RegExPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-zA-Z0-9-_ .,:;()$&amp;@!+|^á-úÁ-Ú\t]+.
        /// </summary>
        public static string RegExTextFieldValidation {
            get {
                return ResourceManager.GetString("RegExTextFieldValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es requerido..
        /// </summary>
        public static string Requerido {
            get {
                return ResourceManager.GetString("Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del rol no debe superar los 250 caracteres..
        /// </summary>
        public static string rolDescripcionTamanno {
            get {
                return ResourceManager.GetString("rolDescripcionTamanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del servicio no debe ser mayor a los 250 caracteres..
        /// </summary>
        public static string servicioDescripcionTamanno {
            get {
                return ResourceManager.GetString("servicioDescripcionTamanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo no debe superar los 250 caracteres.
        /// </summary>
        public static string StringLength250 {
            get {
                return ResourceManager.GetString("StringLength250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo no debe superar los 3000 caracteres.
        /// </summary>
        public static string StringLength3000 {
            get {
                return ResourceManager.GetString("StringLength3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo no debe superar los 50 caracteres.
        /// </summary>
        public static string StringLength50 {
            get {
                return ResourceManager.GetString("StringLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo no debe superar los 500 caracteres.
        /// </summary>
        public static string StringLength500 {
            get {
                return ResourceManager.GetString("StringLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo no debe superar los {0} caracteres.
        /// </summary>
        public static string tamanoString {
            get {
                return ResourceManager.GetString("tamanoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del tipo de indicador no debe superar los 250 caracteres..
        /// </summary>
        public static string tipoIndicadorTamanno {
            get {
                return ResourceManager.GetString("tipoIndicadorTamanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor es requerido..
        /// </summary>
        public static string valorRequerido {
            get {
                return ResourceManager.GetString("valorRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es requerido.
        /// </summary>
        public static string websamplenamerequired {
            get {
                return ResourceManager.GetString("websamplenamerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El identificador es requerido.
        /// </summary>
        public static string websamplenumberrequired {
            get {
                return ResourceManager.GetString("websamplenumberrequired", resourceCulture);
            }
        }
    }
}
