create PROCEDURE [dbo].[pa_ConstructorModificar] 
	@ID_OPERADOR NVARCHAR(20),
	@ID_SERVICIO INT,
	@ID_DIRECCION INT,
	@ID_INDICADOR NVARCHAR(50),
	@ID_CRITERIO NVARCHAR(50),
	@ID_FRECUENCIA INT,
	@ID_DESGLOSE INT,
	@FECHA_INICIAL DATETIME,
	@FECHA_FINAL DATETIME
AS
BEGIN


SELECT SI.* FROM SOLICITUDINDICADOR SI
INNER JOIN SOLICITUDCONSTRUCTOR SC 
ON SI.IDSOLICITUDINDICADOR=SC.IDSOLICITUDINDICADOR AND SI.IDSERVICIO=@ID_SERVICIO
AND SI.IDDIRECCION=@ID_DIRECCION AND SI.IDFRECUENCIA=@ID_FRECUENCIA
AND convert(date,SI.FECHAINICIO)>=convert(date,@FECHA_INICIAL) 
AND convert(date,SI.FECHAFIN)<=convert(date,@FECHA_FINAL)
AND SC.IDOPERADOR=@ID_OPERADOR
INNER JOIN CONSTRUCTOR C ON SC.IDCONSTRUCTOR=C.IDCONSTRUCTOR AND C.IDDESGLOSE=@ID_DESGLOSE
AND C.IDINDICADOR=@ID_INDICADOR
INNER JOIN CONSTRUCTORCRITERIO CC ON C.IDCONSTRUCTOR=CC.IDCONSTRUCTOR
AND CC.IDCRITERIO=@ID_CRITERIO
END