-- Batch submitted through debugger: SQLQuery4.sql|7|0|C:\Users\JOSE~1.MOL\AppData\Local\Temp\~vs8F7E.sql

CREATE PROCEDURE [dbo].[pa_getDetalleAgrupacionesPorOperador] 
				@IdOperador varchar(20),
				@IdSolicitudIndicador uniqueidentifier
AS

SELECT DA.IDDETALLEAGRUPACION as Id_Detalle_Agrupacion,
	   DA.DESCDETALLEAGRUPACION  as Nombre_Detalle_Agrupacion,	   
	   AG.DESCAGRUPACION as Nombre_Agrupacion, 
	   OPE.NOMBREOPERADOR as Nombre_Operador, 
	   CR.DESCCRITERIO as Nombre_Criterio,
	   FR.IDFRECUENCIA as ID_Frecuencia,	   
	   FR.NOMBREFRECUENCIA as Nombre_Frecuencia,
	   FR.CANTIDADMESES as Cantidad_Meses_Frecuencia,	   
	   DE.IDFRECUENCIA as ID_Desglose,	
	   DE.NOMBREFRECUENCIA as Nombre_Desglose,
	   DE.CANTIDADMESES as Cantidad_Meses_Desglose,	   	      
	   IND.IDINDICADOR as ID_Indicador,
	   IND.NOMBREINDICADOR as Nombre_Indicador,
	   NIV.DESCNIVEL as Nivel,
	   REG.VALORLIMITEINFERIOR as Valor_Inferior,
	   REG.VALORLIMITESUPERIOR as Valor_Superior,
	   TVA.IDTIPOVALOR as Id_Tipo_Valor,
	   TVA.DESCRIPCION as Tipo_Valor,
	   TVA.FORMATO as Valor_Formato,
	   CCDA.IDCONSTRUCTORCRITERIO as Id_ConstructorCriterio,
	   CCDALJ.IDCONSTRUCTORCRITERIO as Id_Padre_ConstructorCriterio,
	   DALJ.IDDETALLEAGRUPACION as Id_Padre_Detalle_Agrupacion,
	   DALJ.DESCDETALLEAGRUPACION as Nombre_Padre_Detalle_Agrupacion,
	   SOIN.FECHAINICIO as Fecha_Inicio,	   
	   SOIN.FECHAFIN as Fecha_Fin,
	   SOIN.FechaBaseParaCrearExcel,
	   CCDA.UsaReglaEstadisticaConNivelDetalle, 
	   IND.DescIndicador as Constructor_Criterio_Ayuda,
	   CR.DESCCRITERIO as Descripcion_Criterio,	   
	   SOCO.IDSOLICITUDINDICADOR as Id_Solicitud_Indicador,
	   SOCO.IDSOLICITUDCONTRUCTOR as Id_Solicitud_Constructor,	 	     
	   DIR.NOMBRE as Nombre_Direccion,
	   SER.DESSERVICIO as Nombre_Servicio,
	   

	   CASE 
			WHEN TND.IDNIVELDETALLE = 1
				THEN STUFF((
					  SELECT ', ' + PROVINCIA.NOMBRE
					  FROM PROVINCIA					  
					  FOR XML PATH(''), TYPE).value('.', 'varchar(MAX)'), 1, 1, '')	

			WHEN TND.IDNIVELDETALLE = 2
			THEN STUFF((
					  SELECT ', ' + PROVINCIA.NOMBRE
					  FROM PROVINCIA					  
					  FOR XML PATH(''), TYPE).value('.', 'varchar(MAX)'), 1, 1, '')	

				
		   WHEN TND.IDNIVELDETALLE = 3

		   THEN STUFF((
					  SELECT ', ' + PROVINCIA.NOMBRE
					  FROM PROVINCIA					  
					  FOR XML PATH(''), TYPE).value('.', 'varchar(MAX)'), 1, 1, '')	

									  					
		END AS Tipo_Nivel_Detalle,

		CASE 
			WHEN TND.IDNIVELDETALLE = 1
				THEN STUFF((
					  SELECT ', ' + CONVERT(varchar,PROVINCIA.IDPROVINCIA)
					  FROM PROVINCIA					  
					  FOR XML PATH(''), TYPE).value('.', 'varchar(MAX)'), 1, 1, '')	

			WHEN TND.IDNIVELDETALLE = 2
			THEN STUFF((
					  SELECT ', ' + CONVERT(varchar,PROVINCIA.IDPROVINCIA)
					  FROM PROVINCIA					  
					  FOR XML PATH(''), TYPE).value('.', 'varchar(MAX)'), 1, 1, '')	
				

			
		   WHEN TND.IDNIVELDETALLE = 3
		   THEN STUFF((
					  SELECT ', ' + CONVERT(varchar,PROVINCIA.IDPROVINCIA)
					  FROM PROVINCIA					  
					  FOR XML PATH(''), TYPE).value('.', 'varchar(MAX)'), 1, 1, '')	
				

					  					
		END AS Id_Tipo_Nivel_Detalle,
		TND.TABLA as Tabla_Tipo_Nivel_Detalle,
	    CCDA.IDNIVELDETALLEGENERO
	   	   
FROM DETALLEAGRUPACION AS DA

INNER JOIN OPERADOR AS OPE
ON DA.IDOPERADOR = OPE.IDOPERADOR and 
OPE.ESTADO = 1

INNER JOIN AGRUPACION AS AG
ON DA.IDAGRUPACION = AG.IDAGRUPACION and 
AG.BORRADO = 0

INNER JOIN CONSTRUCTORCRITERIODETALLEAGRUPACION as CCDA
ON DA.IDDETALLEAGRUPACION = CCDA.IDDETALLEAGRUPACION and 
DA.IDAGRUPACION = CCDA.IDAGRUPACION and
DA.IDOPERADOR = CCDA.IDOPERADOR and 
CCDA.borrado=0


INNER JOIN NIVEL as NIV
ON CCDA.IDNIVEL = NIV.IDNIVEL and
NIV.BORRADO = 0

LEFT JOIN REGLA as REG
ON CCDA.IDCONSTRUCTORCRITERIO = REG.IDCONSTRUCTORCRITERIO and
REG.BORRADO = 0

LEFT JOIN TIPOVALOR as TVA
ON CCDA.IDTIPOVALOR = TVA.IDTIPOVALOR

LEFT JOIN TIPONIVELDETALLE as TND
ON CCDA.IDNIVELDETALLE = TND.IDNIVELDETALLE

LEFT JOIN CONSTRUCTORCRITERIODETALLEAGRUPACION as CCDALJ
ON CCDA.IDCONSTRUCTORDETALLEPADRE = CCDALJ.IDCONSTRUCTORCRITERIO
AND CCDALJ.Borrado=0

LEFT JOIN DETALLEAGRUPACION as DALJ
ON DALJ.IDDETALLEAGRUPACION = CCDALJ.IDDETALLEAGRUPACION and 
DALJ.IDAGRUPACION = CCDALJ.IDAGRUPACION and
DALJ.IDOPERADOR = CCDALJ.IDOPERADOR

INNER JOIN CONSTRUCTORCRITERIO as CC
ON CCDA.IDCRITERIO = CC.IDCRITERIO and 
CCDA.IDCONSTRUCTOR = CC.IDCONSTRUCTOR

INNER JOIN CRITERIO as CR
ON CC.IDCRITERIO = CR.IDCRITERIO and
CR.BORRADO = 0

INNER JOIN CONSTRUCTOR as CO
ON CCDA.IDCONSTRUCTOR = CO.IDCONSTRUCTOR

INNER JOIN DIRECCION as DIR
ON CO.IDDIRECCION = DIR.IDDIRECCION

INNER JOIN SOLICITUDCONSTRUCTOR as SOCO
ON CO.IDCONSTRUCTOR = SOCO.IDCONSTRUCTOR and
SOCO.BORRADO = 0 and SOCO.IDOPERADOR = @IdOperador and
SOCO.IDSOLICITUDINDICADOR = @IdSolicitudIndicador 

INNER JOIN SOLICITUDINDICADOR as SOIN
ON SOCO.IDSOLICITUDINDICADOR = SOIN.IDSOLICITUDINDICADOR and
SOIN.BORRADO = 0 and SOIN.ACTIVO = 1 

INNER JOIN SERVICIO as SER
ON SOIN.IDSERVICIO = SER.IDSERVICIO and
SER.BORRADO = 0

INNER JOIN INDICADOR as IND
ON CO.IDINDICADOR = IND.IDINDICADOR and
IND.BORRADO = 0

INNER JOIN FRECUENCIA as FR
ON FR.IDFRECUENCIA = CO.IDFRECUENCIA and
FR.BORRADO = 0

INNER JOIN FRECUENCIA as DE
ON DE.IDFRECUENCIA = CO.IDDESGLOSE and
FR.BORRADO = 0

WHERE DA.BORRADO = 0 and DA.IDOPERADOR = @IdOperador
ORDER BY SOCO.OrdenIndicadorEnExcel, IND.IDINDICADOR,CR.IdCriterio,CCDA.ORDEN,CCDALJ.IDCONSTRUCTORCRITERIO,
		 DALJ.IDDETALLEAGRUPACION,DA.IDDETALLEAGRUPACION,NIV.IDNIVEL