CREATE PROCEDURE [dbo].[pa_RptDetalleAgrupacionPorAgrupacion] 
	--PARÁMETROS
	-- LISTA DE CÓDIGOS DE OPERADORES SEPARADOS POR COMAS (,)
	@pOperadores VARCHAR(MAX) = '',
	-- LISTA DE CÓDIGOS DE AGRUPACIONES SEPARADOS POR COMAS (,)
	@pAgrupaciones VARCHAR(MAX) = ''
AS
BEGIN
	SET NOCOUNT ON;

	--VERIFICAR PARÁMETROS
	SET @pOperadores = ISNULL(@pOperadores, '')
	SET @pAgrupaciones = ISNULL(@pAgrupaciones, '')

	select op.IDOPERADOR,op.NOMBREOPERADOR,da.IDAGRUPACION,a.DESCAGRUPACION,da.IDDETALLEAGRUPACION,da.DESCDETALLEAGRUPACION
	from dbo.OPERADOR as OP with(nolock)
	inner join dbo.DETALLEAGRUPACION as DA with(nolock)
	on op.IDOPERADOR = DA.IDOPERADOR and da.BORRADO = 0 
	inner join dbo.AGRUPACION as A with(nolock)
	on DA.IDAGRUPACION = A.IDAGRUPACION AND a.BORRADO = 0
	where
	op.ESTADO = 1 AND
	(1=(CASE WHEN LEN(@pOperadores)<1 THEN 1 ELSE 0 END) OR da.IDOPERADOR IN (SELECT VALUE FROM DBO.FN_SPLIT (@pOperadores,',')))
	AND
	(1=(CASE WHEN LEN(@pAgrupaciones)<1 THEN 1 ELSE 0 END) OR da.IDAGRUPACION IN (SELECT VALUE FROM DBO.FN_SPLIT (@pAgrupaciones,',')))
	ORDER BY OP.NOMBREOPERADOR,a.DESCAGRUPACION,da.DESCDETALLEAGRUPACION
	
END