//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CategoriasDesagregacion")]
    public class CategoriasDesagregacion
    {
        public CategoriasDesagregacion()
        {
            this.DetalleCategoriaNumerico = new DetalleCategoriaNumerico();
            this.DetalleCategoriaFecha = new DetalleCategoriaFecha();
            this.DetalleCategoriaTexto = new List<DetalleCategoriaTexto>();
            this.EstadoRegistro = new EstadoRegistro();
            this.id = string.Empty;
            this.TieneDetalle = false;
            this.IndicadorAsociados = string.Empty;

        }
        [Key]


        public int idCategoria { get; set; }
        [MaxLength(30)]
        public string Codigo { get; set; }
        [MaxLength(300)]
        public string NombreCategoria { get; set; }
        public int CantidadDetalleDesagregacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }

        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }

        public int idEstado { get; set; }

        public int idTipoDetalle { get; set; }

        public int IdTipoCategoria { get; set; }




        #region Varibles que no forman parte del contexto


        [NotMapped]
        public virtual TipoCategoria TipoCategoria { get; set; }
        [NotMapped]
   
        public bool EsParcial { get; set; }
        public virtual List<DetalleCategoriaTexto> DetalleCategoriaTexto { get; set; }
        [NotMapped]
        public virtual EstadoRegistro EstadoRegistro { get; set; }
        [NotMapped]
        public bool TieneDetalle { get; set; }

        [NotMapped]
        public string id { get; set; }
        [NotMapped]

        public virtual DetalleCategoriaNumerico DetalleCategoriaNumerico { get; set; }
        [NotMapped]

        public virtual DetalleCategoriaFecha DetalleCategoriaFecha { get; set; }

        [NotMapped]

        public string IndicadorAsociados { get; set; }

        [NotMapped]

        public List<string> NoSerialize = new List<string>()
        {
            "idCategoria",
            "IndicadorAsociados",
            "DetalleCategoriaNumerico",
            "idEstado",
            "idTipoDetalle",
            "IdTipoCategoria",
            "id",
            "Estado",
            "EstadoRegistro",
            "idEstado",
            "DetalleCategoriaFecha",
            "DetalleCategoriaTexto",
            "TipoCategoria",
            "FechaModificacion",
            "UsuarioCreacion",
            "FechaCreacion",
            "UsuarioModificacion",
            "EsParcial"

        };


        #endregion

    }
}
