//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DetalleSolicitudFormulario")]
    public partial class DetalleSolicitudFormulario
    {
      
      
        [Key]
        public int IdSolicitud { get; set; }
        public int IdFormulario { get; set; }
        public bool Estado { get; set; }
    

        //public virtual ICollection<Registro> Registro { get; set; }
        //public virtual Solicitud Solicitud { get; set; }
        //public virtual FormularioWeb FormularioWeb { get; set; }
    }
}
