//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DetalleRelacionCategoria")]
    public partial class DetalleRelacionCategoria
    {


        [Key]
        public int idDetalleRelacionCategoria { get; set; }
        public int idRelacionCategoria { get; set; }
        public int idCategoriaDesagregacion { get; set; }
        public bool Estado { get; set; }

        #region Variables Fuera del contexto 

        [NotMapped]
        public string id { get; set; }

        [NotMapped]
        public string relacionId { get; set; }


        [NotMapped]
        public CategoriaDesagregacion CategoriaAtributo { get; set; }


        #endregion

    }
}
