//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DetalleIndicadorCategoria")]
    public partial class DetalleIndicadorCategoria
    {
        public DetalleIndicadorCategoria()
        {
            
        }

        [Key]
        public int idDetalleIndicador { get; set; }
        public int idIndicador { get; set; }
        public int idCategoria { get; set; }
        public int idCategoriaDetalle { get; set; }
        public bool Estado { get; set; }

        [NotMapped]
        public string id { get; set; }

        [NotMapped]
        public string idIndicadorString { get; set; }

        [NotMapped]
        public string idCategoriaString { get; set; }

        [NotMapped]
        public string idCategoriaDetalleString { get; set; }

        [NotMapped]
        public string Etiquetas { get; set; }
    }
}
