//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleIndicadorVariables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleIndicadorVariables()
        {
            this.DetalleRegistroIndicadorVariable = new HashSet<DetalleRegistroIndicadorVariable>();
            this.FormulasCalculo = new HashSet<FormulasCalculo>();
        }
    
        public int idDetalleIndicador { get; set; }
        public int idIndicador { get; set; }
        public string NombreVariable { get; set; }
    
        public virtual CategoriasDesagregacion CategoriasDesagregacion { get; set; }
        public virtual Indicador Indicador { get; set; }

        public virtual ICollection<DetalleRegistroIndicadorVariable> DetalleRegistroIndicadorVariable { get; set; }

        public virtual ICollection<FormulasCalculo> FormulasCalculo { get; set; }
    }
}
