//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRelacionCategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleRelacionCategoria()
        {
            this.DetalleIndicadorCategoria = new HashSet<DetalleIndicadorCategoria>();
        }
    
        public int idDetalleRelacionCategoria { get; set; }
        public int IdRelacionCategoria { get; set; }
        public int idCategoriaAtributo { get; set; }
        public string CategoriaAtributoValor { get; set; }
        public bool Estado { get; set; }
    

        public virtual ICollection<DetalleIndicadorCategoria> DetalleIndicadorCategoria { get; set; }
        public virtual RelacionCategoria RelacionCategoria { get; set; }
    }
}
