//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text;

    [Table("DetalleFormularioWeb")]
    public partial class DetalleFormularioWeb
    {
        public DetalleFormularioWeb () { }

        [Key]
        public int idDetalle { get; set; }
        public int idFormulario { get; set; }
        public int idIndicador { get; set; }
        public string TituloHojas { get; set; }
        public string NotasInformante { get; set; }
        public string NotasEncargado { get; set; }
        public bool Estado { get; set; }

        [NotMapped]
        public virtual Indicador Indicador { get; set; }
        [NotMapped]
        public virtual FormularioWeb formularioweb { get; set; }

        public override string ToString()
        {
            StringBuilder json = new StringBuilder();
            json.Append("{\"Indicador\":\"").Append(this.Indicador.Nombre).Append("\",");
            json.Append("\"Titulo hojas\":\"").Append(this.TituloHojas).Append("\",");
            json.Append("\"Notas FONATEL para el informante\":\"").Append(this.NotasEncargado).Append("\",");
            json.Append("\"Notas informante\":\"").Append(this.NotasInformante).Append("\",");
            json.Append("\"Activo\":\"").Append(this.Estado ? "Si" : "No").Append("\"}");

            return json.ToString();
        }
    }
}
