//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DetalleFuentesRegistro")]
    public partial class DetalleFuentesRegistro
    {

        public DetalleFuentesRegistro()
        {
          
        }

        [Key]
        public int idDetalleFuente { get; set; }
        public int idFuente { get; set; }
        public string NombreDestinatario { get; set; }
        public string CorreoElectronico { get; set; }
        public bool Estado { get; set; }


        #region Atributos no forman parte del contexto

        [NotMapped]
        public string FuenteId { get; set; }

        [NotMapped]
        public string Usuario { get; set; }

        [NotMapped]
        public string Contrasena { get; set; }


        [NotMapped]

        public List<string> NoSerialize = new List<string>()
        {
            "idDetalleFuente",
            "idFuente",
            "Estado",
            "FuenteId",
            "Usuario",
            "Contrasena"


        };


        #endregion

    }
}
