//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DetalleIndicadorCategoria
    {
      
       
        public DetalleIndicadorCategoria()
        {
            this.DetalleRegistroIndicadorCategoria = new HashSet<DetalleRegistroIndicadorCategoria>();
        }
        [Key]
        public int idDetalleIndicador { get; set; }
        public int idIndicador { get; set; }
        public bool Estado { get; set; }
    
        public virtual DetalleRelacionCategoria DetalleRelacionCategoria { get; set; }

        public virtual ICollection<DetalleRegistroIndicadorCategoria> DetalleRegistroIndicadorCategoria { get; set; }
        public virtual Indicador Indicador { get; set; }
    }
}
