//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFuentesRegistro
    {
        public int idDetalleFuente { get; set; }
        public int idFuente { get; set; }
        public string NombreDestinatario { get; set; }
        public string CorreoElectronico { get; set; }
        public bool Estado { get; set; }
    
        public virtual FuentesRegistro FuentesRegistro { get; set; }
    }
}
