//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GB.SIMEF.Entities
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DetalleRegistroIndcadorFonatel")]
    public partial class DetalleRegistroIndicadorCategoriaFonatel
    {
        [Key, Column(Order = 0)]
        public int IdSolicitud { get; set; }


        [Key, Column(Order = 1)]
        public int IdFormulario { get; set; }
        [Key, Column(Order = 2)]
        public int IdIndicador { get; set; }
        public int idCategoria { get; set; }
        public string NombreCategoria { get; set; }
        public int IdTipoCategoria { get; set; }
        public int CantidadDetalleDesagregacion { get; set; }
        public string DetalleCategoriaDesagregacion { get; set; }
        public string RangoMinimo { get; set; }
        public string RangoMaximo { get; set; }
        [NotMapped]
        public string html { get; set; }

        [NotMapped]
        public string Solicitudid { get; set; }
        [NotMapped]
        public string FormularioId { get; set; }
        [NotMapped]
        public string IndicadorId { get; set; }



    }
}
