//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("EstadoRegistro")]
    public partial class EstadoRegistro
    {
       
        public EstadoRegistro()
        {
            
        }

        [Key]
      
        public int idEstado { get; set; }
        public string Nombre { get; set; }
      
        public string Comentarios { get; set; }
      
        public bool Estado { get; set; }

        #region Variables que no forman parte del contexto
        [NotMapped]
      
        public string id { get; set; }
        #endregion
    }
}
