//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FormulasCalculo
    {
        
        public FormulasCalculo()
        {
            this.FormulaNivelCalculoCategoria = new HashSet<FormulaNivelCalculoCategoria>();
            this.FormulasCalculoDetalle = new HashSet<FormulasCalculoDetalle>();
        }
        [Key]
        public int idFormula { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool NivelCalculoTotal { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual DetalleIndicadorVariables DetalleIndicadorVariables { get; set; }
        public virtual EstadoRegistro EstadoRegistro { get; set; }

        public virtual ICollection<FormulaNivelCalculoCategoria> FormulaNivelCalculoCategoria { get; set; }
        public virtual FrecuenciaEnvio FrecuenciaEnvio { get; set; }

        public virtual ICollection<FormulasCalculoDetalle> FormulasCalculoDetalle { get; set; }
    }
}
