//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("FormularioWeb")]

    public partial class FormularioWeb
    {
        public FormularioWeb()
        {
            this.DetalleFormularioWeb = new HashSet<DetalleFormularioWeb>();
            this.DetalleSolicitudFormulario = new HashSet<DetalleSolicitudFormulario>();
            this.ListaIndicadoresObj = new List<Indicador>();

        }
        [Key]
        public int idFormulario { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int CantidadIndicadores { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        
        public int idEstado { get; set; }
        public int idFrecuencia { get; set; }
        

        [NotMapped]
        public string ListaIndicadores { get; set; }

        [NotMapped]
        public string id { get; set; }
        [NotMapped]
        public virtual ICollection<DetalleFormularioWeb> DetalleFormularioWeb { get; set; }
        [NotMapped]
        public virtual ICollection<DetalleSolicitudFormulario> DetalleSolicitudFormulario { get; set; }
        [NotMapped]
        public virtual EstadoRegistro EstadoRegistro { get; set; }
        [NotMapped]
        public virtual FrecuenciaEnvio FrecuenciaEnvio { get; set; }

        [NotMapped]
        public List<Indicador> ListaIndicadoresObj { get; set; }

        [NotMapped]
        public List<string> NoSerialize = new List<string>()
        {
            "id",
            "idFormulario",
            "Codigo",
            "Nombre",
            "Descripcion",
            "CantidadIndicadores",
            "idFrecuencia",
            "ListaIndicadores",
            "DetalleFormularioWeb",
            "DetalleSolicitudFormulario",
            "FrecuenciaEnvio",
            "ListaIndicadoresObj",
            "EstadoRegistro",
            "FechaModificacion",
            "UsuarioCreacion",
            "FechaCreacion",
            "UsuarioModificacion",
            "idEstado"
        };
    }
}
