//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulaNivelCalculoCategoria
    {
        public int idFormulaNivel { get; set; }
        public int idCategoria { get; set; }
    
        public virtual FormulasCalculo FormulasCalculo { get; set; }
    }
}
