//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FormulasCalculoDetalle
    {
        [Key]
        public int idDetalleFormula { get; set; }
        public int idFormula { get; set; }
        public Nullable<int> Constante { get; set; }
        public bool Operador { get; set; }
        public bool IndicadorMC { get; set; }
        public bool IndicadorDSF { get; set; }
    
        public virtual FormulaIndicadorDSF FormulaIndicadorDSF { get; set; }
        public virtual FormulaIndicadorFecha FormulaIndicadorFecha { get; set; }
        public virtual FormulaIndicadorMC FormulaIndicadorMC { get; set; }
        public virtual FormulasCalculo FormulasCalculo { get; set; }
    }
}
