//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("FrecuenciaEnvio")]
    public partial class FrecuenciaEnvio
    {
        
        public FrecuenciaEnvio()
        {
            
        }

        [Key]
        public int IdFrecuenciaEnvio { get; set; }
        public string Nombre { get; set; }
        public int CantidadDia { get; set; }
        public int CantidadMes { get; set; }
        public bool Estado { get; set; }

        #region Variables que no forman parte del contexto
        [NotMapped]
        public string id { get; set; }
        #endregion
    }
}
