//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text;

    [Table("FuentesRegistro")]
    public partial class FuentesRegistro
    {
        
        public FuentesRegistro()
        {
            DetalleFuentesRegistro = new List<DetalleFuentesRegistro>();
        }
        [Key]
        public int idFuente { get; set; }
        public string Fuente { get; set; }
        public int? CantidadDestinatario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }

        public int idEstado { get; set; }

        [NotMapped]
        public  EstadoRegistro EstadoRegistro { get; set; }

        [NotMapped]

        public string id { get; set; }

        [NotMapped]
        public List<DetalleFuentesRegistro> DetalleFuentesRegistro { get; set; }

        public override string ToString()
        {
            StringBuilder json = new StringBuilder();
            json.Append("{\"Fuente\":\"").Append(this.Fuente).Append("\",");
            json.Append("\"Cantidad destinatarios\":").Append(this.CantidadDestinatario).Append("}");
            return json.ToString();
        }
    }
}
