//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operadores()
        {
            this.FormulasOperador = new HashSet<FormulasOperador>();
            this.ReglaComparacionConstante = new HashSet<ReglaComparacionConstante>();
            this.ReglaComparacionIndicador = new HashSet<ReglaComparacionIndicador>();
            this.ReglaSecuencial = new HashSet<ReglaSecuencial>();
        }
    
        public int IdOperador { get; set; }
        public string Nombre { get; set; }
        public string Operador { get; set; }
        public Nullable<int> Tipo { get; set; }
        public bool Estado { get; set; }
    

        public virtual ICollection<FormulasOperador> FormulasOperador { get; set; }

        public virtual ICollection<ReglaComparacionConstante> ReglaComparacionConstante { get; set; }

        public virtual ICollection<ReglaComparacionIndicador> ReglaComparacionIndicador { get; set; }

        public virtual ICollection<ReglaSecuencial> ReglaSecuencial { get; set; }
    }
}
