//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacionSolicitudes
    {
        public int IdProgamacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> NumeroDia { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Repeticiones { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual FrecuenciaEnvio FrecuenciaEnvio { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
