//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registro
    {
        public Registro()
        {
            this.RegistroIndicador = new HashSet<RegistroIndicador>();
        }

        [Key]
        public int idRegistro { get; set; }
        public System.DateTime FechaIncio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual DetalleSolicitudFormulario DetalleSolicitudFormulario { get; set; }
        public virtual EstadoRegistro EstadoRegistro { get; set; }

        public virtual ICollection<RegistroIndicador> RegistroIndicador { get; set; }
    }
}
