//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ReglaAtributosValidos
    {
        [Key]
        public int idCompara { get; set; }
        public int idCategoria { get; set; }
        public int idCategoriaAtributo { get; set; }
        public bool Estado { get; set; }
    
        public virtual ReglaValidacionTipo ReglaValidacionTipo { get; set; }
    }
}
