//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using GB.SIMEF.Resources;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text;

    [Table("ReglaValidacion")]
    public partial class ReglaValidacion
    {
       
        public ReglaValidacion()
        {
            DetalleReglaValidacion = new List<DetalleReglaValidacion>();
        }
        [Key]
        public int idReglaValidacion { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int idIndicador { get; set; }
        public int idEstadoRegistro { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        [NotMapped]
        public EstadoRegistro EstadoRegistro { get; set; }

        [NotMapped]
        public String id{ get; set; }

        [NotMapped]
        public int idCompara { get; set; }


        [NotMapped]
        public String idIndicadorVariableString { get; set; }

        [NotMapped]
        public string idIndicadorString { get; set; }

        [NotMapped]
        public string ListadoTipoReglas { get; set; }

        [NotMapped]
        public List<DetalleReglaValidacion> DetalleReglaValidacion { get; set; }

        [NotMapped]
        public Indicador Indicador { get; set; }

        [NotMapped]
        public string idDetalleReglaValidacion { get; set; }

        public override string ToString()
        {
            StringBuilder json = new StringBuilder();
            json.Append("{\"Código\":\"").Append(this.Codigo).Append("\",");
            json.Append("\"Nombre\":\"").Append(this.Nombre).Append("\",");
            json.Append("\"Tipo de categoría\":\"").Append(this.idIndicador).Append("\",");
            
            json.Append("\"Descripción\":\"").Append(this.Descripcion).Append("\",");

            switch ((int)this.EstadoRegistro.IdEstadoRegistro)
            {
                case (int)Constantes.EstadosRegistro.Desactivado:
                    json.Append("\"Estado\":\"").Append(Enum.GetName(typeof(Constantes.EstadosRegistro), (int)Constantes.EstadosRegistro.Desactivado)).Append("\"}");
                    break;
                case (int)Constantes.EstadosRegistro.Activo:
                    json.Append("\"Estado\":\"").Append(Enum.GetName(typeof(Constantes.EstadosRegistro), (int)Constantes.EstadosRegistro.Activo)).Append("\"}");
                    break;
                case (int)Constantes.EstadosRegistro.Eliminado:
                    json.Append("\"Estado\":\"").Append(Enum.GetName(typeof(Constantes.EstadosRegistro), (int)Constantes.EstadosRegistro.Eliminado)).Append("\"}");
                    break;
                case (int)Constantes.EstadosRegistro.EnProceso:
                    json.Append("\"Estado\":\"").Append(Enum.GetName(typeof(Constantes.EstadosRegistro), (int)Constantes.EstadosRegistro.EnProceso)).Append("\"}");
                    break;
            }




            string resultado = json.ToString();

            return resultado;
        }
    }
}
