//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ReglaComparacionIndicador
    {
        [Key]
        public int idReglaComparacionIndicador { get; set; }
        public int idDetalleReglaValidacion { get; set; }
        public Nullable<int> idDetalleIndicadorVariable { get; set; }
        public Nullable<int> idIndicador { get; set; }

   
        public virtual DetalleReglaValidacion ReglaValidacionTipo { get; set; }
    }
}
