//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text;

    [Table("SolicitudEnvioProgramado")]
    public partial class SolicitudEnvioProgramado
    {
        [Key]
        public int IdSolicitudEnvioProgramado { get; set; }

        public int IdSolicitud { get; set; }

        public int IdFrecuenciaEnvio { get; set; }
        public int CantidadRepeticion { get; set; }
        //public int Dia { get; set; }
        //public int IdMes { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaCiclo { get; set; }
        public bool Estado { get; set; }


        #region VariablesNoMapaeadas

        [NotMapped]
        public string id { get; set; }

        [NotMapped]
        public FrecuenciaEnvio Frecuencia { get; set; }

        [NotMapped]
        public string CodigoSolicitud { get; set; }

        #endregion
        //public virtual FrecuenciaEnvio FrecuenciaEnvio { get; set; }
        //public virtual Solicitud Solicitud { get; set; }

        public override string ToString()
        {
            StringBuilder json = new StringBuilder();
            json.Append("{\"Frecuencia\":\"").Append(this.Frecuencia.Nombre).Append("\",");
            json.Append("\"Cantidad de repeticiones\":").Append(this.CantidadRepeticion).Append(",");
            json.Append("\"Fecha de inicio del ciclo\":\"").Append(this.FechaCiclo).Append("\",");
            json.Append("\"Activo\":\"").Append(this.Estado ? "Si" : "No").Append("\"}");

            return json.ToString();
        }
    }
}
