//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GB.SIMEF.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("SolicitudEnvioProgramado")]
    public partial class SolicitudEnvioProgramado
    {
        [Key]
        public int IdEnvioProgramado { get; set; }

        public int IdSolicitud { get; set; }

        public int IdFrecuencia { get; set; }
        public int CantidadRepiticiones { get; set; }
        //public int Dia { get; set; }
        //public int IdMes { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaCiclo { get; set; }
        public bool Estado { get; set; }


        #region VariablesNoMapaeadas

        [NotMapped]
        public string id { get; set; }

        [NotMapped]
        public string Codigo { get; set; }


        #endregion
        //public virtual FrecuenciaEnvio FrecuenciaEnvio { get; set; }
        //public virtual Solicitud Solicitud { get; set; }
    }
}
